import express from "express";
import clubController from "../controller/clubController.js";
import {clubSchema,updateClubAdminSchema} from "../validators/clubValidation.js";
import validate from "../middleware/validationMiddleWare.js";
import {protect,authorizeRole} from "../middleware/authMiddleWare.js";
const clubRouter=express.Router();
clubRouter.use(protect);
clubRouter.post("/",validate(clubSchema),authorizeRole("SYSTEM_ADMIN"),clubController.createClub);
clubRouter.get("/",clubController.getAllClubs);
clubRouter.get("/:id",clubController.getClubById);
clubRouter.put("/:id",validate(updateClubAdminSchema),authorizeRole("SYSTEM_ADMIN","CLUB_ADMIN"),clubController.updateClub);
clubRouter.delete("/:id",authorizeRole("SYSTEM_ADMIN"),clubController.deleteClub);
clubRouter.patch("/:id/admin",authorizeRole("SYSTEM_ADMIN"),clubController.updateClubAdmin);
clubRouter.get("/:id/history",authorizeRole("SYSTEM_ADMIN","CLUB_ADMIN"),clubController.getFullClubHistory);
export default clubRouter;