import express from "express";
import eventController from "../controller/eventController.js";
import {protect,authorizeRole} from "../middleware/authMiddleWare.js";
import validate from "../middleware/validationMiddleWare.js";
import {eventValidator,updateEventStatus} from "../validators/eventValidator.js";
const eventRouter =express.Router();
eventRouter.use(protect);
eventRouter.post("/",validate(eventValidator),  authorizeRole("SYSTEM_ADMIN","CLUB_ADMIN"),eventController.createEvent);
eventRouter.get("/",eventController.getAllEvents);
eventRouter.get("/:id",eventController.getEventById);
eventRouter.put("/:id",validate(updateEventStatus),authorizeRole("SYSTEM_ADMIN","CLUB_ADMIN"),eventController.updateEvent);
eventRouter.patch("/:id/status",authorizeRole("SYSTEM_ADMIN"),eventController.updateEventStatus);
eventRouter.delete("/:id",authorizeRole("SYSTEM_ADMIN"),eventController.deleteEvent);
eventRouter.get("/:id/club",eventController.getEventByClubId);
export default eventRouter;