import express from "express";
import userController from "../controller/userServiceController.js";
import {protect,authorizeRole} from "../middleware/authMiddleWare.js";
const UserRouter=express.Router();
UserRouter.use(protect);
UserRouter.get("/me",userController.getMyAccount);
UserRouter.get("/all",authorizeRole("SYSTEM_ADMIN","CLUB_ADMIN"),userController.getAllUser);
UserRouter.get("/:id",userController.getUserByID);
UserRouter.get("/:id/pastClub",userController.getPastClub);
UserRouter.put("/me",userController.updateUser);
UserRouter.patch("/:id/role",authorizeRole("SYSTEM_ADMIN"),userController.updateUserRole);
UserRouter.delete("/me/delete",userController.deleteUser);
export default UserRouter;   
